spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhsot:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
