spring:
  application:
    name: client

eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      host-mark: running
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7070
